import { Inter } from 'next/font/google'

import './styles/css/global.css';
import './styles/scss/_global.scss';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Project Roadmap',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  )
}
