import { Inter } from 'next/font/google'
import './styles/css/global.css';
import './styles/scss/_global.scss';

import 'poppins'

export const metadata = {
  title: 'Project Roadmap',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body suppressHydrationWarning={true}>
        {children}
      </body>
    </html>
  )
}
